### ISSUE TITLE
Project 3: Twitter Client

### ISSUE THREAD

**Issue by neerajakshid** [neerajakshid/Twitter-Client#1]
My Twitter Client app is complete, please review. /cc @codepathreview @codepath

**Comment by neerajakshid** [comment]
I have started implementing the VideoView for loading videos but couldn't complete it yesterday.. I am working on it now..

Regards

**Comment by codepathreview** [comment]
:+1: Excellent work again. Great to see you put in the effort to turn in a polished assignment.. A few notes after checking out the code:
- Good to see you were able to format the timestamp cleanly (correctly externalized logic to `Utilities`)
- Nice to see you used the `SwipeRefreshLayout` for easy timeline refreshes
- Good to see you refreshed the timeline after composing a new tweet
- Special mention for all the additional stories that you completed yourself (good to see you learned from previous assignments and implemented in this one).
- Good to see you added `ActiveAndroid` annotations to the models for offline usage
- Nice touch with the character count being displayed while the user composes a tweet.

Here's a detailed [Project 3 Feedback Guide here](http://courses.codepath.com/snippets/intro_to_android/project_3_feedback) which covers the most common issues with this submitted project. Read through the feedback guide point-by-point to determine how you could improve your submission. 

Let us know if you have any other thoughts or questions about this assignment. Hopefully by now you feel pretty comfortable with all the major pieces to basic Android apps (Views, Controllers, ActionBar, Navigation, Models, Authentication, API Communication, Persistence, et al) and see how they all fit together. We are close now to a turning point in the course where you should be hitting a "critical mass" towards your knowledge of Android.

**Comment by neerajakshid** [comment]
Thanks for the review!!

This is a great assignment to work on as it involved implementation of lot of concepts we covered over the past weeks. Working on this project helped me learn more as it involved much reading.
